# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Jess & Jay"
tagline:          'Jess & Jay'
description:      'June 11th, 2016<br><br>Palm Door on Sabine<br>401 Sabine Street<br>Austin, TX 78701 (<a href="https://goo.gl/maps/kUREv422jtS2">map</a>)<hr>'
url:              http://jessandjay.github.io/
baseurl:          /

author:
  name:           'Jay H'
  url:            http://www.jehosafet.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jessandjay/jessandjay.github.io
