# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Jess & Jay"
tagline:          'Jess & Jay'
description:      "June 11th, 2016<br><br>203 Heritage Oaks Ln<br>Houston, TX 77024<hr><i>More details soon!</i>"
url:              http://jessandjay.info
baseurl:          /

author:
  name:           'Jay H'
  url:            http://www.jehosafet.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jessandjay/jessandjay.github.io
